### ISSUE TITLE
Add the link to the second webinar

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#234]
@AnneSchoenauer and @Tilmon whenver you're ready you can edit inst/config/iframe.yml and replace the current (placeholder) URL with the real URL for "Webinar 2" [here](https://github.com/2DegreesInvesting/tiltWebTool/blob/main/inst/config/iframe.yml#L17).

Currently we're using the "Webinar 1" twice.

Look for this

```
  method2:
     header: "Webinar 2"
     src: "https://www.youtube.com/embed/WXNCYmXq7nw?si=xqGETa2mOsGSELg8"
     width: 560
     height: 315
```
