### ISSUE TITLE
Edit the feedback form on Drive or replace the link in the app

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#237]
@AnneSchoenauer and @Tilmon

Currently the feedback form in the app is a generic template for customer feedback.  

You have two options:

* One: Don't touch the app and edit the form for make it look as you want. Find the link for editors here:
  * https://github.com/2DegreesInvesting/tiltWebTool/issues/235
* Two: Generate a new form, get the link for users and replace it in the app [here](https://github.com/2DegreesInvesting/tiltWebTool/blob/main/inst/config/welcome.yml#L47).

Look for this:

```yaml
  card3:
    p1: >
      ### We Value Your Feedback

      We strive for transparency and welcome input from financial institutions,
      researchers, and NGOs. Join the *tilt* community and share your feedback
      [here](https://docs.google.com/document/d/1IfOxPWZ41lXpTQKg_t-vZBKyP-DrX1do-c68TvMLbZM/pub).
```
