### ISSUE TITLE
Add required text

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#79]
> You can find the text [here](https://docs.google.com/document/d/1XUzQKwJE7gPcZvT811iS8NYGibO0ro1W4ob-fpWoYhk/edit) --Anne

**Comment by AnneSchoenauer** [comment]
@Tilmon I think this is high priority

**Comment by maurolepore** [comment]
@AnneSchoenauer you edit the text in this file

https://github.com/2DegreesInvesting/tiltWebTool/blob/main/inst/config.yml

You may also add new sections following the same format. For example you  may add a `header` and `body` for a `newsection` like this:

```yaml
default:
  newsection:
    header: You can write any text in a single line.
    body: >
      If you need multiple lines use the '>' symbol.

      You may write multiple pagraphraphs and use markdown format, for
      example this is *italics* and this is **bold**.
    footer: This is a footer.
```
